version: '3.9'
services:
  matomo:
    image: matomo
    container_name: matomo
    restart: always
    ports:
      - '80'
    links:
      - db:db
    labels:
      - 'traefik.enable=true'
      #Routers
      - 'traefik.http.routers.matomo.rule=Host(`matomo.julian-husson.com`)'
      - 'traefik.http.routers.matomo.entrypoints=websecure'
      - 'traefik.http.routers.matomo.tls.certresolver=resolver'
      #Services
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
    volumes:
      - matomo:/var/www/html
    env_file:
      - env/.env-matomo
    depends_on:
      - db
    networks:
      - web
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    container_name: matomo-db
    volumes:
      - db:/var/lib/mysql
    env_file:
      - env/.env-db
    networks:
      - web
volumes:
  db:
  matomo:
networks:
  web:
    external: true
