version: '3.9'
services:
  matomo:
    image: matomo
    container_name: matomo
    restart: always
    ports:
      - '80'
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_TABLES_PREFIX=mat_
      - MATOMO_DATABASE_USERNAME=/run/secrets/matomo_db_username
      - MATOMO_DATABASE_PASSWORD=/run/secrets/matomo_db_password
      - MATOMO_DATABASE_DBNAME=/run/secrets/matomo_db_name
    links:
      - db:db
    labels:
      - 'traefik.enable=true'
      #Routers
      - 'traefik.http.routers.matomo.rule=Host(`matomo.julian-husson.com`)'
      - 'traefik.http.routers.matomo.entrypoints=websecure'
      - 'traefik.http.routers.matomo.tls.certresolver=resolver'
      #Services
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
    volumes:
      - matomo:/var/www/html
    secrets:
      - matomo_db_username
      - matomo_db_password
      - matomo_db_name
    networks:
      - web
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    container_name: matomo-db
    environment:
      - MYSQL_DATABASE=/run/secrets/mysql_database
      - MYSQL_USER=/run/secrets/mysql_user
      - MYSQL_PASSWORD=/run/secrets/mysql_password
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
    volumes:
      - db:/var/lib/mysql
    secrets:
      - mysql_user
      - mysql_password
      - mysql_database
secrets:
  matomo_db_username:
    file: "./secrets/matomo_db_username.txt"
  matomo_db_password:
    file: "./secrets/matomo_db_password.txt"
  matomo_db_name:
    file: "./secrets/matomo_db_name.txt"
  mysql_database:
    file: "./secrets/mysql_database.txt"
  mysql_user:
    file: "secrets/mysql_user.txt"
  mysql_password:
    file: "./secrets/mysql_password.txt"
volumes:
  db:
  matomo:
networks:
  web:
    external: true
